require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PlotsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Plot. As you add validations to Plot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlotsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all plots as @plots" do
      plot = Plot.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:plots)).to eq([plot])
    end
  end

  describe "GET #show" do
    it "assigns the requested plot as @plot" do
      plot = Plot.create! valid_attributes
      get :show, params: {id: plot.to_param}, session: valid_session
      expect(assigns(:plot)).to eq(plot)
    end
  end

  describe "GET #new" do
    it "assigns a new plot as @plot" do
      get :new, params: {}, session: valid_session
      expect(assigns(:plot)).to be_a_new(Plot)
    end
  end

  describe "GET #edit" do
    it "assigns the requested plot as @plot" do
      plot = Plot.create! valid_attributes
      get :edit, params: {id: plot.to_param}, session: valid_session
      expect(assigns(:plot)).to eq(plot)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Plot" do
        expect {
          post :create, params: {plot: valid_attributes}, session: valid_session
        }.to change(Plot, :count).by(1)
      end

      it "assigns a newly created plot as @plot" do
        post :create, params: {plot: valid_attributes}, session: valid_session
        expect(assigns(:plot)).to be_a(Plot)
        expect(assigns(:plot)).to be_persisted
      end

      it "redirects to the created plot" do
        post :create, params: {plot: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Plot.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved plot as @plot" do
        post :create, params: {plot: invalid_attributes}, session: valid_session
        expect(assigns(:plot)).to be_a_new(Plot)
      end

      it "re-renders the 'new' template" do
        post :create, params: {plot: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested plot" do
        plot = Plot.create! valid_attributes
        put :update, params: {id: plot.to_param, plot: new_attributes}, session: valid_session
        plot.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested plot as @plot" do
        plot = Plot.create! valid_attributes
        put :update, params: {id: plot.to_param, plot: valid_attributes}, session: valid_session
        expect(assigns(:plot)).to eq(plot)
      end

      it "redirects to the plot" do
        plot = Plot.create! valid_attributes
        put :update, params: {id: plot.to_param, plot: valid_attributes}, session: valid_session
        expect(response).to redirect_to(plot)
      end
    end

    context "with invalid params" do
      it "assigns the plot as @plot" do
        plot = Plot.create! valid_attributes
        put :update, params: {id: plot.to_param, plot: invalid_attributes}, session: valid_session
        expect(assigns(:plot)).to eq(plot)
      end

      it "re-renders the 'edit' template" do
        plot = Plot.create! valid_attributes
        put :update, params: {id: plot.to_param, plot: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested plot" do
      plot = Plot.create! valid_attributes
      expect {
        delete :destroy, params: {id: plot.to_param}, session: valid_session
      }.to change(Plot, :count).by(-1)
    end

    it "redirects to the plots list" do
      plot = Plot.create! valid_attributes
      delete :destroy, params: {id: plot.to_param}, session: valid_session
      expect(response).to redirect_to(plots_url)
    end
  end

end
